matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd cli
      script:
        - python -m unittest discover

    - language: node_js
      node_js: 8
      before_script:
        - cd daemon
      script:
        - npm install
        - npm test

    - language: node_js
      node_js: 8
      before_script:
        - cd web
      script:
        - npm install
        - npm test